# Generated by Django 4.0.2 on 2022-02-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_tag_project_vote_ratio_project_vote_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tag',
            new_name='tags',
        ),
    ]
