# Generated by Django 4.0.2 on 2022-02-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_tag_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('DOWN', 'DOWNVOTE'), ('UP', 'UPVOTE')], max_length=200),
        ),
    ]
