# Generated by Django 4.0.2 on 2022-02-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('UP', 'UPVOTE'), ('DOWN', 'DOWNVOTE')], max_length=200),
        ),
    ]
