# Generated by Django 4.0.2 on 2022-02-23 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_birth_date_remove_profile_location_and_more'),
        ('projects', '0008_alter_review_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='users.profile'),
        ),
    ]
