# Generated by Django 4.0.2 on 2022-02-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('DOWN', 'DOWNVOTE'), ('UP', 'UPVOTE')], max_length=200),
        ),
    ]
